import { qgen, PrimitiveParser as PP, ArrayParser as AP, CompositeParser as CP } from "qgen";
import { BigNumber } from "bignumber.js";
import currency from "currency.js";
type PgType_pg_catalog = {
    "bool": boolean;
    "bytea": Buffer;
    "char": string;
    "name": string[];
    "int8": bigint;
    "int2": number;
    "int2vector": number[];
    "int4": number;
    "regproc": string;
    "text": string;
    "oid": string;
    "tid": string;
    "xid": string;
    "cid": string;
    "oidvector": string[];
    "json": any;
    "xml": any;
    "_xml": any[];
    "_json": any[];
    "table_am_handler": string;
    "_xid8": string[];
    "index_am_handler": string;
    "point": PP.Point;
    "lseg": PP.Point[];
    "path": PP.Path;
    "box": PP.Box;
    "polygon": PP.Polygon;
    "line": PP.Line;
    "_line": PP.Line[];
    "cidr": string;
    "_cidr": string[];
    "float4": number;
    "float8": number;
    "unknown": string;
    "circle": PP.Circle;
    "_circle": PP.Circle[];
    "macaddr8": string;
    "_macaddr8": string[];
    "money": currency;
    "_money": currency[];
    "macaddr": string;
    "inet": string;
    "_bool": boolean[];
    "_bytea": Buffer[];
    "_char": string[];
    "_name": string[][];
    "_int2": number[];
    "_int2vector": number[][];
    "_int4": number[];
    "_regproc": string[];
    "_text": string[];
    "_tid": string[];
    "_xid": string[];
    "_cid": string[];
    "_oidvector": string[][];
    "_bpchar": string[];
    "_varchar": string[];
    "_int8": bigint[];
    "_point": PP.Point[];
    "_lseg": PP.Point[][];
    "_path": PP.Path[];
    "_box": PP.Box[];
    "_float4": number[];
    "_float8": number[];
    "_polygon": PP.Polygon[];
    "_oid": string[];
    "aclitem": string;
    "_aclitem": string[];
    "_macaddr": string[];
    "_inet": string[];
    "bpchar": string;
    "varchar": string;
    "date": Date;
    "time": string;
    "timestamp": Date;
    "_timestamp": Date[];
    "_date": Date[];
    "_time": string[];
    "timestamptz": Date;
    "_timestamptz": Date[];
    "interval": PP.IPostgresInterval;
    "_interval": PP.IPostgresInterval[];
    "_numeric": BigNumber[];
    "_cstring": string[];
    "timetz": string;
    "_timetz": string[];
    "bit": string;
    "_bit": string[];
    "varbit": string;
    "_varbit": string[];
    "numeric": BigNumber;
    "refcursor": string;
    "_refcursor": string[];
    "regprocedure": string;
    "regoper": string;
    "regoperator": string;
    "regclass": string;
    "regtype": string;
    "_regprocedure": string[];
    "_regoper": string[];
    "_regoperator": string[];
    "_regclass": string[];
    "_regtype": string[];
    "record": string;
    "cstring": string;
    "any": string;
    "anyarray": string;
    "void": string;
    "trigger": string;
    "language_handler": string;
    "internal": string;
    "anyelement": string;
    "_record": string[];
    "anynonarray": string;
    "_txid_snapshot": string[];
    "uuid": string;
    "_uuid": string[];
    "txid_snapshot": string;
    "fdw_handler": string;
    "_pg_lsn": string[];
    "tsm_handler": string;
    "anyenum": string;
    "tsvector": string;
    "tsquery": string;
    "gtsvector": string;
    "_tsvector": string[];
    "_gtsvector": string[];
    "_tsquery": string[];
    "regconfig": string;
    "_regconfig": string[];
    "regdictionary": string;
    "_regdictionary": string[];
    "jsonb": any;
    "_jsonb": any[];
    "anyrange": string;
    "event_trigger": string;
    "int4range": string;
    "_int4range": string[];
    "numrange": string;
    "_numrange": string[];
    "tsrange": string;
    "_tsrange": string[];
    "tstzrange": string;
    "_tstzrange": string[];
    "daterange": string;
    "_daterange": string[];
    "int8range": string;
    "_int8range": string[];
    "jsonpath": string;
    "_jsonpath": string[];
    "regnamespace": string;
    "_regnamespace": string[];
    "regrole": string;
    "_regrole": string[];
    "regcollation": string;
    "_regcollation": string[];
    "int4multirange": string;
    "nummultirange": string;
    "tsmultirange": string;
    "tstzmultirange": string;
    "datemultirange": string;
    "int8multirange": string;
    "anymultirange": string;
    "anycompatiblemultirange": string;
    "_pg_snapshot": string[];
    "xid8": string;
    "anycompatible": string;
    "anycompatiblearray": string;
    "anycompatiblenonarray": string;
    "anycompatiblerange": string;
    "_int4multirange": string[];
    "_nummultirange": string[];
    "_tsmultirange": string[];
    "_tstzmultirange": string[];
    "_datemultirange": string[];
    "_int8multirange": string[];
};
type PgType_public = {
    "_yn": string[];
    "yn": string;
    "_text_name": string[];
    "text_name": string;
    "_text_title": string[];
    "text_title": string;
    "_text_content": string[];
    "text_content": string;
    "_text_markdown": string[];
    "text_markdown": string;
    "_text_short_content": string[];
    "text_short_content": string;
    "_text_word": string[];
    "text_word": string;
    "_text_url": string[];
    "text_url": string;
    "_text_email": string[];
    "text_email": string;
    "_text_phone_number": string[];
    "text_phone_number": string;
    "_text_filepath": string[];
    "text_filepath": string;
    "_text_mime": string[];
    "text_mime": string;
    "_inventory_item": {
        "name": string | null;
        "supplier_id": number | null;
        "price": BigNumber | null;
    }[];
    "inventory_item": {
        "name": string | null;
        "supplier_id": number | null;
        "price": BigNumber | null;
    };
};
type PgType_types = {
    "_mncst": {
        "type": string | null;
        "at": Date | null;
        "kinds": string[] | null;
    }[];
    "mncst": {
        "type": string | null;
        "at": Date | null;
        "kinds": string[] | null;
    };
    "_movein": {
        "type": string | null;
        "at": Date | null;
    }[];
    "movein": {
        "type": string | null;
        "at": Date | null;
    };
    "_parkng": {
        "yn": (string | null) | null;
        "cnt": number | null;
    }[];
    "parkng": {
        "yn": (string | null) | null;
        "cnt": number | null;
    };
    "_price": {
        "type": string | null;
        "price": currency | null;
        "depst": currency | null;
    }[];
    "price": {
        "type": string | null;
        "price": currency | null;
        "depst": currency | null;
    };
};
type PgType = {
    "pg_catalog": PgType_pg_catalog;
    "public": PgType_public;
    "types": PgType_types;
};
const PgParser: any = [[16, "pg_catalog", "bool", PP.parseBool], [17, "pg_catalog", "bytea", PP.parseBytea], [18, "pg_catalog", "char", PP.noParse], [19, "pg_catalog", "name", AP.create(PP.parseNullable(PP.noParse))], [20, "pg_catalog", "int8", PP.parseBigInteger], [21, "pg_catalog", "int2", PP.parseInteger], [22, "pg_catalog", "int2vector", AP.create(PP.parseNullable(PP.parseInteger))], [23, "pg_catalog", "int4", PP.parseInteger], [24, "pg_catalog", "regproc", PP.noParse], [25, "pg_catalog", "text", PP.noParse], [26, "pg_catalog", "oid", PP.noParse], [27, "pg_catalog", "tid", PP.noParse], [28, "pg_catalog", "xid", PP.noParse], [29, "pg_catalog", "cid", PP.noParse], [30, "pg_catalog", "oidvector", AP.create(PP.parseNullable(PP.noParse))], [114, "pg_catalog", "json", PP.parseJson], [142, "pg_catalog", "xml", PP.parseXml], [143, "pg_catalog", "_xml", AP.create(PP.parseNullable(PP.parseXml))], [199, "pg_catalog", "_json", AP.create(PP.parseNullable(PP.parseJson))], [269, "pg_catalog", "table_am_handler", PP.noParse], [271, "pg_catalog", "_xid8", AP.create(PP.parseNullable(PP.noParse))], [325, "pg_catalog", "index_am_handler", PP.noParse], [600, "pg_catalog", "point", PP.parsePoint], [601, "pg_catalog", "lseg", AP.create(PP.parseNullable(PP.parsePoint))], [602, "pg_catalog", "path", PP.parsePath], [603, "pg_catalog", "box", PP.parseBox], [604, "pg_catalog", "polygon", PP.parsePolygon], [628, "pg_catalog", "line", PP.parseLine], [629, "pg_catalog", "_line", AP.create(PP.parseNullable(PP.parseLine))], [650, "pg_catalog", "cidr", PP.noParse], [651, "pg_catalog", "_cidr", AP.create(PP.parseNullable(PP.noParse))], [700, "pg_catalog", "float4", PP.parseNumber], [701, "pg_catalog", "float8", PP.parseNumber], [705, "pg_catalog", "unknown", PP.noParse], [718, "pg_catalog", "circle", PP.parseCircle], [719, "pg_catalog", "_circle", AP.create(PP.parseNullable(PP.parseCircle))], [774, "pg_catalog", "macaddr8", PP.noParse], [775, "pg_catalog", "_macaddr8", AP.create(PP.parseNullable(PP.noParse))], [790, "pg_catalog", "money", (raw: string) => currency(raw)], [791, "pg_catalog", "_money", AP.create(PP.parseNullable((raw: string) => currency(raw)))], [829, "pg_catalog", "macaddr", PP.noParse], [869, "pg_catalog", "inet", PP.noParse], [1000, "pg_catalog", "_bool", AP.create(PP.parseNullable(PP.parseBool))], [1001, "pg_catalog", "_bytea", AP.create(PP.parseNullable(PP.parseBytea))], [1002, "pg_catalog", "_char", AP.create(PP.parseNullable(PP.noParse))], [1003, "pg_catalog", "_name", AP.create(PP.parseNullable(AP.create(PP.parseNullable(PP.noParse))))], [1005, "pg_catalog", "_int2", AP.create(PP.parseNullable(PP.parseInteger))], [1006, "pg_catalog", "_int2vector", AP.create(PP.parseNullable(AP.create(PP.parseNullable(PP.parseInteger))))], [1007, "pg_catalog", "_int4", AP.create(PP.parseNullable(PP.parseInteger))], [1008, "pg_catalog", "_regproc", AP.create(PP.parseNullable(PP.noParse))], [1009, "pg_catalog", "_text", AP.create(PP.parseNullable(PP.noParse))], [1010, "pg_catalog", "_tid", AP.create(PP.parseNullable(PP.noParse))], [1011, "pg_catalog", "_xid", AP.create(PP.parseNullable(PP.noParse))], [1012, "pg_catalog", "_cid", AP.create(PP.parseNullable(PP.noParse))], [1013, "pg_catalog", "_oidvector", AP.create(PP.parseNullable(AP.create(PP.parseNullable(PP.noParse))))], [1014, "pg_catalog", "_bpchar", AP.create(PP.parseNullable(PP.noParse))], [1015, "pg_catalog", "_varchar", AP.create(PP.parseNullable(PP.noParse))], [1016, "pg_catalog", "_int8", AP.create(PP.parseNullable(PP.parseBigInteger))], [1017, "pg_catalog", "_point", AP.create(PP.parseNullable(PP.parsePoint))], [1018, "pg_catalog", "_lseg", AP.create(PP.parseNullable(AP.create(PP.parseNullable(PP.parsePoint))))], [1019, "pg_catalog", "_path", AP.create(PP.parseNullable(PP.parsePath))], [1020, "pg_catalog", "_box", AP.create(PP.parseNullable(PP.parseBox))], [1021, "pg_catalog", "_float4", AP.create(PP.parseNullable(PP.parseNumber))], [1022, "pg_catalog", "_float8", AP.create(PP.parseNullable(PP.parseNumber))], [1027, "pg_catalog", "_polygon", AP.create(PP.parseNullable(PP.parsePolygon))], [1028, "pg_catalog", "_oid", AP.create(PP.parseNullable(PP.noParse))], [1033, "pg_catalog", "aclitem", PP.noParse], [1034, "pg_catalog", "_aclitem", AP.create(PP.parseNullable(PP.noParse))], [1040, "pg_catalog", "_macaddr", AP.create(PP.parseNullable(PP.noParse))], [1041, "pg_catalog", "_inet", AP.create(PP.parseNullable(PP.noParse))], [1042, "pg_catalog", "bpchar", PP.noParse], [1043, "pg_catalog", "varchar", PP.noParse], [1082, "pg_catalog", "date", PP.parseDate], [1083, "pg_catalog", "time", PP.noParse], [1114, "pg_catalog", "timestamp", PP.parseDate], [1115, "pg_catalog", "_timestamp", AP.create(PP.parseNullable(PP.parseDate))], [1182, "pg_catalog", "_date", AP.create(PP.parseNullable(PP.parseDate))], [1183, "pg_catalog", "_time", AP.create(PP.parseNullable(PP.noParse))], [1184, "pg_catalog", "timestamptz", PP.parseDate], [1185, "pg_catalog", "_timestamptz", AP.create(PP.parseNullable(PP.parseDate))], [1186, "pg_catalog", "interval", PP.parseDate], [1187, "pg_catalog", "_interval", AP.create(PP.parseNullable(PP.parseDate))], [1231, "pg_catalog", "_numeric", AP.create(PP.parseNullable(BigNumber))], [1263, "pg_catalog", "_cstring", AP.create(PP.parseNullable(PP.noParse))], [1266, "pg_catalog", "timetz", PP.noParse], [1270, "pg_catalog", "_timetz", AP.create(PP.parseNullable(PP.noParse))], [1560, "pg_catalog", "bit", PP.noParse], [1561, "pg_catalog", "_bit", AP.create(PP.parseNullable(PP.noParse))], [1562, "pg_catalog", "varbit", PP.noParse], [1563, "pg_catalog", "_varbit", AP.create(PP.parseNullable(PP.noParse))], [1700, "pg_catalog", "numeric", BigNumber], [1790, "pg_catalog", "refcursor", PP.noParse], [2201, "pg_catalog", "_refcursor", AP.create(PP.parseNullable(PP.noParse))], [2202, "pg_catalog", "regprocedure", PP.noParse], [2203, "pg_catalog", "regoper", PP.noParse], [2204, "pg_catalog", "regoperator", PP.noParse], [2205, "pg_catalog", "regclass", PP.noParse], [2206, "pg_catalog", "regtype", PP.noParse], [2207, "pg_catalog", "_regprocedure", AP.create(PP.parseNullable(PP.noParse))], [2208, "pg_catalog", "_regoper", AP.create(PP.parseNullable(PP.noParse))], [2209, "pg_catalog", "_regoperator", AP.create(PP.parseNullable(PP.noParse))], [2210, "pg_catalog", "_regclass", AP.create(PP.parseNullable(PP.noParse))], [2211, "pg_catalog", "_regtype", AP.create(PP.parseNullable(PP.noParse))], [2249, "pg_catalog", "record", PP.noParse], [2275, "pg_catalog", "cstring", PP.noParse], [2276, "pg_catalog", "any", PP.noParse], [2277, "pg_catalog", "anyarray", PP.noParse], [2278, "pg_catalog", "void", PP.noParse], [2279, "pg_catalog", "trigger", PP.noParse], [2280, "pg_catalog", "language_handler", PP.noParse], [2281, "pg_catalog", "internal", PP.noParse], [2283, "pg_catalog", "anyelement", PP.noParse], [2287, "pg_catalog", "_record", AP.create(PP.parseNullable(PP.noParse))], [2776, "pg_catalog", "anynonarray", PP.noParse], [2949, "pg_catalog", "_txid_snapshot", AP.create(PP.parseNullable(PP.noParse))], [2950, "pg_catalog", "uuid", PP.noParse], [2951, "pg_catalog", "_uuid", AP.create(PP.parseNullable(PP.noParse))], [2970, "pg_catalog", "txid_snapshot", PP.noParse], [3115, "pg_catalog", "fdw_handler", PP.noParse], [3221, "pg_catalog", "_pg_lsn", AP.create(PP.parseNullable(PP.noParse))], [3310, "pg_catalog", "tsm_handler", PP.noParse], [3500, "pg_catalog", "anyenum", PP.noParse], [3614, "pg_catalog", "tsvector", PP.noParse], [3615, "pg_catalog", "tsquery", PP.noParse], [3642, "pg_catalog", "gtsvector", PP.noParse], [3643, "pg_catalog", "_tsvector", AP.create(PP.parseNullable(PP.noParse))], [3644, "pg_catalog", "_gtsvector", AP.create(PP.parseNullable(PP.noParse))], [3645, "pg_catalog", "_tsquery", AP.create(PP.parseNullable(PP.noParse))], [3734, "pg_catalog", "regconfig", PP.noParse], [3735, "pg_catalog", "_regconfig", AP.create(PP.parseNullable(PP.noParse))], [3769, "pg_catalog", "regdictionary", PP.noParse], [3770, "pg_catalog", "_regdictionary", AP.create(PP.parseNullable(PP.noParse))], [3802, "pg_catalog", "jsonb", PP.parseJson], [3807, "pg_catalog", "_jsonb", AP.create(PP.parseNullable(PP.parseJson))], [3831, "pg_catalog", "anyrange", PP.noParse], [3838, "pg_catalog", "event_trigger", PP.noParse], [3904, "pg_catalog", "int4range", PP.noParse], [3905, "pg_catalog", "_int4range", AP.create(PP.parseNullable(PP.noParse))], [3906, "pg_catalog", "numrange", PP.noParse], [3907, "pg_catalog", "_numrange", AP.create(PP.parseNullable(PP.noParse))], [3908, "pg_catalog", "tsrange", PP.noParse], [3909, "pg_catalog", "_tsrange", AP.create(PP.parseNullable(PP.noParse))], [3910, "pg_catalog", "tstzrange", PP.noParse], [3911, "pg_catalog", "_tstzrange", AP.create(PP.parseNullable(PP.noParse))], [3912, "pg_catalog", "daterange", PP.noParse], [3913, "pg_catalog", "_daterange", AP.create(PP.parseNullable(PP.noParse))], [3926, "pg_catalog", "int8range", PP.noParse], [3927, "pg_catalog", "_int8range", AP.create(PP.parseNullable(PP.noParse))], [4072, "pg_catalog", "jsonpath", PP.noParse], [4073, "pg_catalog", "_jsonpath", AP.create(PP.parseNullable(PP.noParse))], [4089, "pg_catalog", "regnamespace", PP.noParse], [4090, "pg_catalog", "_regnamespace", AP.create(PP.parseNullable(PP.noParse))], [4096, "pg_catalog", "regrole", PP.noParse], [4097, "pg_catalog", "_regrole", AP.create(PP.parseNullable(PP.noParse))], [4191, "pg_catalog", "regcollation", PP.noParse], [4192, "pg_catalog", "_regcollation", AP.create(PP.parseNullable(PP.noParse))], [4451, "pg_catalog", "int4multirange", PP.noParse], [4532, "pg_catalog", "nummultirange", PP.noParse], [4533, "pg_catalog", "tsmultirange", PP.noParse], [4534, "pg_catalog", "tstzmultirange", PP.noParse], [4535, "pg_catalog", "datemultirange", PP.noParse], [4536, "pg_catalog", "int8multirange", PP.noParse], [4537, "pg_catalog", "anymultirange", PP.noParse], [4538, "pg_catalog", "anycompatiblemultirange", PP.noParse], [5039, "pg_catalog", "_pg_snapshot", AP.create(PP.parseNullable(PP.noParse))], [5069, "pg_catalog", "xid8", PP.noParse], [5077, "pg_catalog", "anycompatible", PP.noParse], [5078, "pg_catalog", "anycompatiblearray", PP.noParse], [5079, "pg_catalog", "anycompatiblenonarray", PP.noParse], [5080, "pg_catalog", "anycompatiblerange", PP.noParse], [6150, "pg_catalog", "_int4multirange", AP.create(PP.parseNullable(PP.noParse))], [6151, "pg_catalog", "_nummultirange", AP.create(PP.parseNullable(PP.noParse))], [6152, "pg_catalog", "_tsmultirange", AP.create(PP.parseNullable(PP.noParse))], [6153, "pg_catalog", "_tstzmultirange", AP.create(PP.parseNullable(PP.noParse))], [6155, "pg_catalog", "_datemultirange", AP.create(PP.parseNullable(PP.noParse))], [6157, "pg_catalog", "_int8multirange", AP.create(PP.parseNullable(PP.noParse))], [16402, "public", "_yn", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16403, "public", "yn", PP.noParse], [16405, "public", "_text_name", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16406, "public", "text_name", PP.noParse], [16407, "public", "_text_title", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16408, "public", "text_title", PP.noParse], [16409, "public", "_text_content", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16410, "public", "text_content", PP.noParse], [16411, "public", "_text_markdown", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16412, "public", "text_markdown", PP.noParse], [16413, "public", "_text_short_content", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16414, "public", "text_short_content", PP.noParse], [16415, "public", "_text_word", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16416, "public", "text_word", PP.noParse], [16417, "public", "_text_url", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16418, "public", "text_url", PP.noParse], [16419, "public", "_text_email", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16420, "public", "text_email", PP.noParse], [16421, "public", "_text_phone_number", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16422, "public", "text_phone_number", PP.noParse], [16423, "public", "_text_filepath", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16424, "public", "text_filepath", PP.noParse], [16425, "public", "_text_mime", AP.create(PP.parseNullable(PP.parseNullable(PP.noParse)))], [16426, "public", "text_mime", PP.noParse], [32873, "types", "_mncst", AP.create(PP.parseNullable(CP.create([["type", PP.parseNullable(PP.noParse)], ["at", PP.parseNullable(PP.parseDate)], ["kinds", PP.parseNullable(AP.create(PP.parseNullable(PP.noParse)))]])))], [32874, "types", "mncst", CP.create([["type", PP.parseNullable(PP.noParse)], ["at", PP.parseNullable(PP.parseDate)], ["kinds", PP.parseNullable(AP.create(PP.parseNullable(PP.noParse)))]])], [32876, "types", "_movein", AP.create(PP.parseNullable(CP.create([["type", PP.parseNullable(PP.noParse)], ["at", PP.parseNullable(PP.parseDate)]])))], [32877, "types", "movein", CP.create([["type", PP.parseNullable(PP.noParse)], ["at", PP.parseNullable(PP.parseDate)]])], [32879, "types", "_parkng", AP.create(PP.parseNullable(CP.create([["yn", PP.parseNullable(PP.parseNullable(PP.noParse))], ["cnt", PP.parseNullable(PP.parseInteger)]])))], [32880, "types", "parkng", CP.create([["yn", PP.parseNullable(PP.parseNullable(PP.noParse))], ["cnt", PP.parseNullable(PP.parseInteger)]])], [50191, "types", "_price", AP.create(PP.parseNullable(CP.create([["type", PP.parseNullable(PP.noParse)], ["price", PP.parseNullable((raw: string) => currency(raw))], ["depst", PP.parseNullable((raw: string) => currency(raw))]])))], [50192, "types", "price", CP.create([["type", PP.parseNullable(PP.noParse)], ["price", PP.parseNullable((raw: string) => currency(raw))], ["depst", PP.parseNullable((raw: string) => currency(raw))]])], [73729, "public", "_inventory_item", AP.create(PP.parseNullable(CP.create([["name", PP.parseNullable(PP.noParse)], ["supplier_id", PP.parseNullable(PP.parseInteger)], ["price", PP.parseNullable(BigNumber)]])))], [73730, "public", "inventory_item", CP.create([["name", PP.parseNullable(PP.noParse)], ["supplier_id", PP.parseNullable(PP.parseInteger)], ["price", PP.parseNullable(BigNumber)]])]];
export default qgen().setup<PgType>(PgParser);
